### PR TITLE
Modify MasqDaemon to allow multiple chains

### PR DESCRIPTION
**Pull request by caboteria**
MasqDaemon was designed to have only one chain since it masquerades all traffic leaving the node. In my use case I want to copy MasqDaemon into my project to manage multiple chains so that limitation was a problem.

Now the chain object is passed into the MasqDaemon so the masqChain var is no longer needed. This makes some implicit parameter passing explicit, but otherwise ip-masq-agent's functionality hasn't changed.

Here's an example from my project (called PureLB) of how I'm passing a chain name into MasqDaemon: https://gitlab.com/purelb/purelb/-/blob/114-egress-gateway/internal/egress/announcer_egress.go#L124

### CODE REVIEW

**Comment by jingyuanliang** [comment]
Eliminating globals generally looks good, but I don't see inject a chain other than the one specified by `--masq-chain` here?

**Comment by caboteria** [comment]
Thank you for looking at this! I think my original top-comment wasn't clear so I extended it to make my intent clearer, i.e., ip-masq-agent functionality is the same but now I can use the code in https://gitlab.com/purelb/purelb

**Pull request closed without merging**
